# Generated by Django 6.0.6 on 2026-06-06 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Rasm')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('thumbnail', models.ImageField(upload_to='clip_thumbnails/', verbose_name='Thumbnail')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiylik (soniya)')),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Klip',
                'verbose_name_plural': 'Kliplar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Baho')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Qism raqami')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbs/')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiylik (daqiqa)')),
                ('is_free', models.BooleanField(default=True, verbose_name='Bepul')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
                'ordering': ['season__number', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likelar',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='Original nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Poster')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Banner')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Treyler URL')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (daqiqa)')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Reyting')),
                ('imdb_rating', models.FloatField(blank=True, null=True, verbose_name='IMDB reyting')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='Til')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Rejissyor')),
                ('cast', models.TextField(blank=True, verbose_name='Aktyorlar')),
                ('quality', models.CharField(choices=[('SD', 'SD'), ('HD', 'HD'), ('FHD', 'Full HD'), ('4K', '4K')], default='HD', max_length=5, verbose_name='Sifat')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Holat')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Yoqtirganlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ko'rish",
                'verbose_name_plural': "Ko'rishlar",
                'ordering': ['-watched_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saqlangan kino',
                'verbose_name_plural': 'Saqlangan kinolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Mavsum raqami')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Nomi')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='seasons/')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mavsum',
                'verbose_name_plural': 'Mavzumlar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Kichik sarlavha')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
    ]
