# Generated by Django 6.0.6 on 2026-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
